### ISSUE TITLE
Crashing after turning on Notification Sync, then crashes on open.

### ISSUE THREAD

**Issue by ShadowEO** [AsteroidOS/WinSteroid#2]
I can reproduce this behavior on two machines, both with wildly different specs, with relative ease. It seems to happen with the following cases:

- Notifications become cleared through action center
- After connecting to the watch on app open
- Toggling Focus Assist

I can reset the application and then reopen the app and it will work for a little bit, but then crash again. I had it do so to me just about 5 minutes ago when I toggled Focus Assist and Cortana showed her digest notification of what all was missed.

You've got a very wonderful AsteroidOS client for Windows in the works here! Can't wait to see how it grows and becomes more stable (and more fully functional)! In fact, you've given me a new reason to use my old Dory again (as I have a Windows 10-based tablet that I'm loving the idea of having a smartwatch connected to)!

Edit: My apologies, I'm sure you need the build numbers for my test machines, I tested the app under both of the most recent RS5 builds (the previous one and the current 17704 build that dropped today) on both x86 and x86_64 systems.

I also saved a copy of the event generated in the Windows event log by the application which can be found here: https://drive.google.com/open?id=1aZvC2OrzB2w7qYKrhc73YmvgyNVD8_AB

**Comment by thunderluca** [comment]
@ShadowEO thank you!

Currently I'm developing and testing WinSteroid only on RTM builds, but I'll give a try with a Windows Insider VM to understand which components/parts of codes cause this problems (seeing your Event Viewer report, I don't like the generic Windows.UI.Xaml.dll error, especially if it's coming from an Insider build where a lot of components are unreliable). 

Currently the Microsoft Store is releasing a new version, 0.2.3.0, where I fixed some bugs related to notifications, let me know if new version solve some of the bugs reported :-)

**Comment by ShadowEO** [comment]
Just updated on my machines. The first one I'm testing on seems stable! Tested toggling focus assist and everything was fine, moved around the app and didn't experience any crashes yet!

I still have the x86_64 machine to test on, but considering your UWP app doesn't have any specific arch requirements, I think it's fixed!

I'm going to leave it running for a little while more, if I don't receive a crash, I'll close the issue ticket!

**Comment by ShadowEO** [comment]
Well, it seems that your newest update fixed a lot of the crashing. I seem to still get some minor crashes, but I think that's because I'm trying to test with two machines. I noticed one instance crashes if another connects, which may just be a limitation of btsyncd (just my speculation, I haven't yet dug into AsteroidOS to begin tinkering but your app may help me start doing so!!).

ANYWAY! Because my original crash report has been fixed, I'm going to go ahead and close this ticket. If I can pinpoint any others, I'll open a new ticket (might even just set back up VS so I can run it through a debugger while I'm using it for you!)
